# Generated by Django 5.2.5 on 2025-08-28 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcardtransaction',
            name='related_booking',
        ),
        migrations.RemoveField(
            model_name='virtualcardtransaction',
            name='virtual_card',
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('external', 'External')], default='app', max_length=20),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage for app bookings', max_digits=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dealer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['source'], name='bookings_source_2e1530_idx'),
        ),
        migrations.DeleteModel(
            name='VirtualCardTransaction',
        ),
    ]
