# Generated by Django 5.2.5 on 2025-08-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0002_remove_virtualcardtransaction_related_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('booking', 'Booking Completion'), ('payout', 'Payout'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'balance_transactions',
            },
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True, help_text='Reason for commission change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commission_history',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_availability',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('customer_card', 'Customer Card'), ('virtual_card', 'Dealer Virtual Card'), ('external', 'External (No Payment Record)')], default='customer_card', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cardealing.virtualcard'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='cardealing.dealerprofile'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardealing.booking'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='related_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardealing.payoutrequest'),
        ),
        migrations.AddField(
            model_name='commissionhistory',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to='cardealing.dealerprofile'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions_code_893bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions_is_acti_5031c3_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardealing.promotion'),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='cardealing.service'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['dealer'], name='balance_tra_dealer__32bff1_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['transaction_type'], name='balance_tra_transac_c4cf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['created_at'], name='balance_tra_created_240890_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionhistory',
            index=models.Index(fields=['dealer'], name='commission__dealer__ba9085_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionhistory',
            index=models.Index(fields=['effective_date'], name='commission__effecti_faf357_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceavailability',
            index=models.Index(fields=['service'], name='service_ava_service_332b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceavailability',
            index=models.Index(fields=['is_active'], name='service_ava_is_acti_27225d_idx'),
        ),
    ]
