# Generated by Django 5.2.5 on 2025-09-16 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0004_customerprofile_latitude_customerprofile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.RemoveIndex(
            model_name='dealerprofile',
            name='dealer_prof_has_ext_23de09_idx',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Invalid phone number format')]),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='bank_account_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d{8,20}$', 'Invalid bank account number')]),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='bank_routing_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Invalid routing number')]),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage for app bookings', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=2, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardealing.subscriptionplan'),
        ),
    ]
