# Generated by Django 5.2.5 on 2025-09-16 10:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0005_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'service_history',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'technicians',
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_externa_bddd51_idx',
        ),
        migrations.RenameField(
            model_name='virtualcard',
            old_name='cvv',
            new_name='last_four_digits',
        ),
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Invalid card number')]),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardealing.booking'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardealing.service'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='cardealing.vehicle'),
        ),
        migrations.AddField(
            model_name='technician',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='cardealing.dealerprofile'),
        ),
        migrations.AddIndex(
            model_name='servicehistory',
            index=models.Index(fields=['vehicle'], name='service_his_vehicle_4c8ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicehistory',
            index=models.Index(fields=['completed_at'], name='service_his_complet_aabcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['dealer'], name='technicians_dealer__3a8b7d_idx'),
        ),
    ]
