# Generated by Django 5.2.5 on 2025-09-20 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0006_servicehistory_technician_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('phone', 'Phone OTP'), ('email', 'Email Verification'), ('national_id', 'National ID')], max_length=20)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_verifications',
                'indexes': [models.Index(fields=['user'], name='customer_ve_user_id_4393ac_idx'), models.Index(fields=['status'], name='customer_ve_status_f2c8e6_idx')],
                'unique_together': {('user', 'verification_type')},
            },
        ),
    ]
