# Generated by Django 5.2.5 on 2025-09-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='zktiko_id',
            new_name='zkteco_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_payroll.shift', verbose_name='Shift'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='hr_payroll__employe_4c2ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='hr_payroll__date_4ae44c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'timestamp'], name='hr_payroll__employe_a47a15_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['device', 'timestamp'], name='hr_payroll__device__9a0204_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['zkteco_id'], name='hr_payroll__zkteco__15c6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='hr_payroll__employe_246cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='zkdevice',
            index=models.Index(fields=['ip_address', 'port'], name='hr_payroll__ip_addr_683927_idx'),
        ),
    ]
